name: Deploy Vite Frontend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Check build output directory
        run: |
          echo "Listing workspace root files:"
          ls -la
          echo "Listing dist directory contents:"
          ls -la dist

      - name: Upload build files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.FRONTEND_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "~/frontend/dist"

      - name: SSH and Deploy Nginx with Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONTEND_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Stopping and removing existing vite-app container if it exists..."
            docker stop vite-app || true
            docker rm vite-app || true

            echo "Removing old vite-app image if it exists..."
            docker rmi vite-app || true

            echo "Creating Dockerfile in ~/frontend directory..."
            cat > ~/frontend/Dockerfile <<EOF
            FROM nginx:alpine
            COPY dist /usr/share/nginx/html
            EXPOSE 80
            EOF

            echo "Building new vite-app Docker image..."
            cd ~/frontend
            docker build -t vite-app .

            echo "Running new vite-app container..."
            docker run -d -p 80:80 --name vite-app vite-app
